### ISSUE TITLE
NLP

### ISSUE THREAD

**Issue by nbansal2211** [TakuSemba/CropMe#11]
Process: com.allcode.palacio, PID: 12452
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.allcode.palacio/com.allcode.palacio.activities.newDesigns.ImageCroppingActivity}: java.lang.NullPointerException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2404)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2464)
        at android.app.ActivityThread.access$900(ActivityThread.java:172)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:146)
        at android.app.ActivityThread.main(ActivityThread.java:5653)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
        at com.takusemba.cropme.CropLayout.setUri(CropLayout.java:142)
        at com.allcode.palacio.activities.newDesigns.ImageCroppingActivity.initViews(ImageCroppingActivity.java:36)
        at com.allcode.palacio.activities.newDesigns.ImageCroppingActivity.onCreate(ImageCroppingActivity.java:25)
        at android.app.Activity.performCreate(Activity.java:5541)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2368)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2464) 
        at android.app.ActivityThread.access$900(ActivityThread.java:172) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:146) 
        at android.app.ActivityThread.main(ActivityThread.java:5653) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107) 
        at dalvik.system.NativeStart.main(Native Method) 
06-03 19:38:23.198 12452-12557/com.allcode.palacio E/HttpRestService: CustomParser not found

**Comment by TakuSemba** [comment]
I'm closing this due to the lack of information.
