### ISSUE TITLE
Circle Cropping is not working

### ISSUE THREAD

**Issue by shaon2016** [TakuSemba/CropMe#21]

**Comment by qwaskhaled** [comment]
Hello. I got this report from Firebase and it's from one of our users. Could you check it, please?

Fatal Exception: java.lang.IllegalArgumentException: cannot use a recycled source in createBitmap
       at android.graphics.Bitmap.createBitmap(Bitmap.java:882)
       at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:807)
       at com.takusemba.cropme.CropLayout$crop$1.invoke(CropLayout.kt:189)
       at com.takusemba.cropme.CropLayout$crop$1.invoke(CropLayout.kt:32)
       at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
